# =====================================================
#                 SEssentials Configuration
# =====================================================
# This file controls the core behavior of SEssentials.
# Reload with: /sessentials reload
# =====================================================

# Master enable switch for the plugin
enabled: true

# Check for updates on startup
check-updates: true

# Global feature toggles
features:
  enabled: true			  # Enable all plugin features
  events: true			  # Enable all plugin events
  commands: true			# Enable all plugin commands

# General plugin settings
settings:
  debug-mode: false
  force-gamemode: true
  default-gamemode: "survival"

# Default messages
messages:
  prefix: ""
  join: "&8[&a+&8] &f"
  quit: "&8[&c-&8] &f"
  reloaded: "&aSEssentials has been reloaded."
  subcommand-unknown: " &cUnknown subcommand. Try "
  permission-denied: "&cYou don't have the required permission to use this command."