name: SEssentials
version: 0.2.5
main: me.daivdmajholt.sessentials.Main
api-version: 1.19
commands:
  sessentials:
    description: This command is for plugin support.
    usage: /sessentials help
  bal:
    description: This commands shows yours and other players' balance.
    usage: /bal (player)
  balance:
    description: This commands shows yours and other players' balance.
    usage: /balance (player)¨
  fly:
    description: This command toggles flight mode for a player.
    usage: /fly (player)
  god:
    description: This command toggles god mode for a player.
    usage: /god (player)
  buy:
    description: This command shows the online store link for the player.
    usage: /buy
  warp:
    description: This command teleports a player to any warps.
    usage: /warp (warp name) (player)
  warps:
    description: This command shows all warps that exist.
    usage: /warps
  discord:
    description: This command shows the discord link for the player.
    usage: /discord
  rm:
    description: This commands handles ranks and permissions.
    usage: /rm help
  rankmanager:
    description: This commands handles ranks and permissions.
    usage: /rankmanager help
  eco:
    description: This command changes the players' balance.
    usage: /eco (give/remove/set) (player) (amount)
  economy:
    description: This command changes the players' balance.
    usage: /economy (give/remove/set) (player) (amount)
  spawn:
    description: This command teleports you to spawn.
    usage: /spawn (player)
  setspawn:
    description: This command sets the spawn location.
    usage: /setspawn (rank id)
  gamemode:
    description: This command sets a player's gamemode.
    usage: /gamemode (survival/creative/adventure/spectator) (player)
  gm:
    description: This command sets a player's gamemode.
    usage: /gm (survival/creative/adventure/spectator) (player)
  gmc:
    description: This command sets a player's gamemode to creative.
    usage: /gmc
  gma:
    description: This command sets a player's gamemode to adventure.
    usage: /gma
  gms:
    description: This command sets a player's gamemode to survivel.
    usage: /gms
  gmsp:
    description: This command sets a player's gamemode to spectator.
    usage: /gmsp
  give:
    description: This command gives a player a specific  item.
    usage: /give (player) (item) (amount)