name: SEssentials
version: 0.1.1
main: me.daivdmajholt.sessentials.Main
api-version: 1.19
commands:
  sessentials:
    description: This command is for plugin support.
    usage: /sessentials help
  gamemode:
    description: This command sets a player's gamemode.
    usage: /gamemode (survival/creative/adventure/spectator) (player)
  gm:
    description: This command sets a player's gamemode.
    usage: /gm (survival/creative/adventure/spectator) (player)
  gmc:
    description: This command sets a player's gamemode to creative.
    usage: /gmc
  gma:
    description: This command sets a player's gamemode to adventure.
    usage: /gma
  gms:
    description: This command sets a player's gamemode to survivel.
    usage: /gms
  gmsp:
    description: This command sets a player's gamemode to spectator.
    usage: /gmsp
  give:
      description: This command gives a player a spefic item.