name: SEssentials
version: 0.3.7
main: me.daivdmajholt.sessentials.Main
api-version: 1.19
commands:
  sessentials:
    description: This command is for plugin support.
    usage: /sessentials help
  bal:
    description: This commands shows yours and other players' balance.
    usage: /bal (player)
  money:
    description: This commands shows yours and other players' balance.
    usage: /money (player)
  balance:
    description: This commands shows yours and other players' balance.
    usage: /balance (player)
  realname:
    description: Discover your and other players' real username.
    usage: /realname (player)
  ping:
    description: This commands shows yours and other players' ping.
    usage: /ping (player)
  speed:
    description: This commands controls your and other players' flying/running speed.
    usage: /speed (speed) (player)
  online:
    description: Discover total online player count.
    usage: /online
  onlinestaff:
    description: Discover total online staff count.
    usage: /onlinestaff
  fly:
    description: This command toggles flight mode for a player.
    usage: /fly (player)
  god:
    description: This command toggles god mode for a player.
    usage: /god (player)
  seed:
    description: This command shows the world seed.
    usage: /seed
  buy:
    description: This command shows the online store link for the player.
    usage: /buy
  heal:
    description: This command will fully restore a players health.
    usage: /heal (player)
  feed:
    description: This command will fill a player's hunger.
    usage: /feed (player)
  stop:
    description: This command will stop the server.
    usage: /stop
  kick:
    description: This command kicks any player for any reason provided.
    usage: /kick (player) (reason)
  ban:
    description: This command bans any player who is below the executor's rank, regardless of the reason.
    usage: /ban (player) (reason)
  bans:
    description: This command will show all players who are banned on this server.
    usage: /bans
  unban:
    description: This command unbans a specific player by name.
    usage: /unban (name)
  unbanip:
    description: This command unbans a specific player using the player’s UUID.
    usage: /unbanip (uuid)
  store:
    description: This command shows the online store link for the player.
    usage: /store
  warp:
    description: This command teleports a player to any warps.
    usage: /warp (warp name) (player)
  warps:
    description: This command shows all warps that exist.
    usage: /warps
  discord:
    description: This command shows the discord link for the player.
    usage: /discord
  rm:
    description: This commands handles ranks and permissions.
    usage: /rm help
  clearchat:
    description: This command clears the chat for all players.
    usage: /clearchat
  cc:
    description: This command clears the chat for all players.
    usage: /cc
  clearlag:
    description: This command clears all dropped items on the ground.
    usage: /clearlag
  cl:
    description: This command clears all dropped items on the ground.
    usage: /cl
  rankmanager:
    description: This commands handles ranks and permissions.
    usage: /rankmanager help
  eco:
    description: This command changes the players' balance.
    usage: /eco (give/remove/set) (player) (amount)
  economy:
    description: This command changes the players' balance.
    usage: /economy (give/remove/set) (player) (amount)
  spawn:
    description: This command teleports you to spawn.
    usage: /spawn (player)
  setspawn:
    description: This command sets the spawn location.
    usage: /setspawn (rank id)
  gamemode:
    description: This command sets a player's gamemode.
    usage: /gamemode (survival/creative/adventure/spectator) (player)
  gm:
    description: This command sets a player's gamemode.
    usage: /gm (survival/creative/adventure/spectator) (player)
  gmc:
    description: This command sets a player's gamemode to creative.
    usage: /gmc
  gma:
    description: This command sets a player's gamemode to adventure.
    usage: /gma
  gms:
    description: This command sets a player's gamemode to survivel.
    usage: /gms
  gmsp:
    description: This command sets a player's gamemode to spectator.
    usage: /gmsp
  give:
    description: This command gives a player a specific  item.
    usage: /give (player) (item) (amount)
  invensee:
    description: This command opens another players inventory.
    usage: /invensee (player)
  rank:
    description: This commands handles ranks and permissions.
    usage: /rank help
  broadcast:
    description: This command broadcasts a colored message.
    usage: /broadcast (message)
  bc:
    description: This command broadcasts a colored message.
    usage: /bc (message)
  eat:
    description: This command will fill a player's hunger.
    usage: /eat (player)
  strike:
    description: This command will strike a player.
    usage: /strike (player)
  smite:
    description: This command will smite a player.
    usage: /smite (player)
  clearinventory:
    description: This command will clear a player's entire inventory.
    usage: /clearinventory (player)
  clear:
    description: This command will clear your inventory.
    usage: /clear
  tpall:
    description: This command teleports all players to another player's location.
    usage: /tpall (player)
  teleportall:
    description: This command teleports all players to another player's location.
    usage: /teleportall (player)
  vanish:
    description: This command can vanish any player from all other players.
    usage: /vanish (player)
  workbench:
    description: This command opens a workbench menu for players.
    usage: /workbench (player)
  craft:
    description: This command opens a workbench menu for players.
    usage: /craft (player)
  anvil:
    description: This command opens a anvil menu for players.
    usage: /anvil (player)
  enderchest:
    description: This command opens a enderchest menu for players.
    usage: /enderchest (player)